---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactgraph
  labels:
    app: contactgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactgraph
  template:
    metadata:
      labels:
        app: contactgraph
    spec:
      containers:
        - name: contactgraph
          image: platelk/contactgraph:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 10Gi
              cpu: 2
---
apiVersion: v1
kind: Service
metadata:
  name: contactgraph
spec:
  type: NodePort
  selector:
    app: contactgraph
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: contactgraph
spec:
  ingressClassName: "nginx"
  rules:
    - host: "contactgraph.squidreef.fr"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contactgraph
                port:
                  name: http